In [1]:
text="Welcome to python"

In [4]:
lst=text.split(sep=' ')
lst

['Welcome', 'to', 'python']

In [4]:
text2="Revanth is working on python"
list2=text2.split(maxsplit=2)
list2

['Revanth', 'is', 'working on python']

## Split syntax
### .split(seperator, maxsplit)

In [12]:
numbers=input("Enter 2 numbers")
num1,num2=numbers.split()
sum=int(num1)+int(num2)
print(sum)

55

In [1]:
x= input("Enter a 3 word message")

In [4]:
a,b,c=x.split()
# The number of variables on left of assignment operator and no of values
# generated by split function must be same

In [3]:
a,b,c

('I', 'write', 'code')

In [9]:
values=input("Enter 2 integers")
num1,num2=values.split()
sum=int(num1)+int(num2)
print("sum is", sum)

sum is 33

In [10]:
test="I am groot in avengers"
test.split(sep=' ',maxsplit=3)

['I', 'am', 'groot', 'in avengers']

In [12]:
test="I am groot in avengers"
test.split(sep=' ',maxsplit=2)
# maxsplit makes 2 splits and the remaining will be grouped as a single one

['I', 'am', 'groot in avengers']

In [14]:
s1='Hi@Hi@Hi@Hi@Hi'
s1.split('@',2) # we can also use this format for separator and mxsplit

['Hi', 'Hi', 'Hi@Hi@Hi']

In [15]:
s2='Hi#Hi#Hi#Hi'
s2.split('#')

['Hi', 'Hi', 'Hi', 'Hi']

# While loop

In [20]:
x=1
while(x<10):
    print('value is',x)
    x=x+1
print("Done")

value is 1
value is 2
value is 3
value is 4
value is 5
value is 6
value is 7
value is 8
value is 9
Done

In [25]:

x=1
while(x<10):
    if(x==7):
        break
    print('value is',x)
    x=x+1
    
print("Done")

value is 1
value is 2
value is 3
value is 4
value is 5
value is 6
Done

In [28]:
i=0
while (i<10):
    
    i=i+1
    if(i==5):
        continue
    print('value of i is',i)
print("Done")

value of i is 1
value of i is 2
value of i is 3
value of i is 4
value of i is 6
value of i is 7
value of i is 8
value of i is 9
value of i is 10
Done

In [1]:
i=0;
while i <9:
    i=i+1
    if(i==3):
        continue
    print(i)
print("loop done")

1
2
4
5
6
7
8
9
loop done

In [3]:
## Pass Statement
## Its basically a no operation statement
i=10
if i<20:
    pass

In [5]:
my_list=['apple','banana','orange','mango','grapes']
size=len(my_list)
size

5

In [10]:
i=0
while i<size:
    if my_list[i]=='mango':
        print("mango found")
        break;
    i=i+1
else:
    print("mango not found")

mango found

In [12]:
i=0
while i<4:
    i=i+1
    if(i%2!=0):
        pass
        print('Hi',end=' ')
    else:
        print(i,end=' ')

Hi 2 Hi 4

In [13]:
i=0
while i<4:
    i=i+1
    if(i%2!=0):
        continue
        print('Hi',end=' ')
    else:
        print(i,end=' ')

2 4

In [14]:
i=0
while i<4:
    i=i+1
    if(i%2!=0):
        break
        print('Hi',end=' ')
    else:
        print(i,end=' ')

In [1]:
x=123
for i in x:
    print(i)

TypeError: 'int' object is not iterable

In [2]:
x='abcdef'
i='i'
while i in x:
    print(i)

In [3]:
x='abcd'
for i in x: # here x is initially taken as abcd
    print(i,end=' ')
    x=x.upper()

a b c d

In [7]:
'a@bc@d'.split('@',10)

['a', 'bc', 'd']

In [8]:
'a b c '.split(' ',6)

['a', 'b', 'c', '']